###
POST http://localhost:9000/api/category
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjJiNGMyMmZiNGY3YTk0OTk5M2E2ZCIsImZpcnN0bmFtZSI6IlRlc3QiLCJsYXN0bmFtZSI6IlRlc3QiLCJwYXNzd29yZCI6IiQyYiQwNCRqQ3NwazYuaTB0cDBIeFJVcWt4dVlPaHEySWtJTmdrTE4wYmk3RENTeFFibHpaWU42dHJwVyIsImVtYWlsIjoib3l1a2EyQGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjhUMDk6MzQ6NTguNDM1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjhUMDk6MzQ6NTguNDM1WiIsIl9fdiI6MH0sImlhdCI6MTY3OTk5NjIwNCwiZXhwIjoxNjgyNTg4MjA0fQ.u0-T8EJz2GoDWQsZ54U1GsYB6eCqNoQTu799PXPHdCI

{
  "categoryName":"Menu"
}

###
get http://localhost:9000/api/category
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjJiNGMyMmZiNGY3YTk0OTk5M2E2ZCIsImZpcnN0bmFtZSI6IlRlc3QiLCJsYXN0bmFtZSI6IlRlc3QiLCJwYXNzd29yZCI6IiQyYiQwNCRqQ3NwazYuaTB0cDBIeFJVcWt4dVlPaHEySWtJTmdrTE4wYmk3RENTeFFibHpaWU42dHJwVyIsImVtYWlsIjoib3l1a2EyQGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjhUMDk6MzQ6NTguNDM1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjhUMDk6MzQ6NTguNDM1WiIsIl9fdiI6MH0sImlhdCI6MTY3OTk5NjIwNCwiZXhwIjoxNjgyNTg4MjA0fQ.u0-T8EJz2GoDWQsZ54U1GsYB6eCqNoQTu799PXPHdCI


###
put http://localhost:9000/api/category/641d11c015b932fc8fd23aad
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjJiNGMyMmZiNGY3YTk0OTk5M2E2ZCIsImZpcnN0bmFtZSI6IlRlc3QiLCJsYXN0bmFtZSI6IlRlc3QiLCJwYXNzd29yZCI6IiQyYiQwNCRqQ3NwazYuaTB0cDBIeFJVcWt4dVlPaHEySWtJTmdrTE4wYmk3RENTeFFibHpaWU42dHJwVyIsImVtYWlsIjoib3l1a2EyQGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjhUMDk6MzQ6NTguNDM1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjhUMDk6MzQ6NTguNDM1WiIsIl9fdiI6MH0sImlhdCI6MTY3OTk5NjIwNCwiZXhwIjoxNjgyNTg4MjA0fQ.u0-T8EJz2GoDWQsZ54U1GsYB6eCqNoQTu799PXPHdCI

{
  "categoryName":"Menus"
}


###
get http://localhost:9000/api/category/641d11b815b932fc8fd23aaa
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MjJiNGMyMmZiNGY3YTk0OTk5M2E2ZCIsImZpcnN0bmFtZSI6IlRlc3QiLCJsYXN0bmFtZSI6IlRlc3QiLCJwYXNzd29yZCI6IiQyYiQwNCRqQ3NwazYuaTB0cDBIeFJVcWt4dVlPaHEySWtJTmdrTE4wYmk3RENTeFFibHpaWU42dHJwVyIsImVtYWlsIjoib3l1a2EyQGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjMtMDMtMjhUMDk6MzQ6NTguNDM1WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDMtMjhUMDk6MzQ6NTguNDM1WiIsIl9fdiI6MH0sImlhdCI6MTY3OTk5NjIwNCwiZXhwIjoxNjgyNTg4MjA0fQ.u0-T8EJz2GoDWQsZ54U1GsYB6eCqNoQTu799PXPHdCI